name: Daily Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/radzenhq/radzen-blazor.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories --no-edit || echo "No changes to merge"

      - name: Push changes
        run: |
          git push origin master
